# Generated by Django 3.1.7 on 2021-05-02 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cumba_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image',
        ),
        migrations.RemoveField(
            model_name='image',
            name='image_ppoi',
        ),
    ]
