# Generated by Django 3.1.7 on 2021-05-02 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cumba_api', '0002_auto_20210502_0813'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image',
            field=models.ImageField(default='image', upload_to='product/images/'),
            preserve_default=False,
        ),
    ]
