# Generated by Django 3.1.7 on 2021-05-05 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cumba_api', '0003_auto_20210504_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.SlugField(),
        ),
    ]
