# Generated by Django 3.1.7 on 2021-05-05 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cumba_api', '0004_auto_20210505_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_url',
            field=models.SlugField(default='Null'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='product/images/'),
        ),
    ]
